// src/data/triviaData.ts
// ─────────────────────────────────────────────────────────────────────────────
// Runtime access to the trivia question banks.
//
// ⚠️ The JSON in ./trivia/ is GENERATED by tools/convert-trivia.js from the raw
// dumps in tools/raw/. Never hand-edit it — to drop a question add its id to
// tools/blocklist.json and re-run the converter.
//
// Penalties deliberately reuse the Truth or Dare scale (PENALTY / getPenalty in
// gameData.ts) rather than inventing a second one, so:
//   • the Sip Intensity stepper on the Players screen applies to Trivia free,
//   • "2 sips" means the same thing in both modes.
// ─────────────────────────────────────────────────────────────────────────────

import { PENALTY, PenaltyContext, formatPenalty, getPenalty } from './gameData';
import { TriviaQuestion, WedgeId, WEDGE_IDS } from './trivia/types';
import { shuffle } from '../utils/random';

import artsQuestions from './trivia/arts.json';
import entertainmentQuestions from './trivia/entertainment.json';
import geographyQuestions from './trivia/geography.json';
import historyQuestions from './trivia/history.json';
import scienceQuestions from './trivia/science.json';
import sportQuestions from './trivia/sport.json';

// JSON imports widen `difficulty` to number and `type` to string, so the cast
// is unavoidable. ValidateTrivia.js is what actually guarantees the shape.
const asPool = (raw: unknown): TriviaQuestion[] => raw as TriviaQuestion[];

export const WEDGE_POOLS: Record<WedgeId, TriviaQuestion[]> = {
  geography: asPool(geographyQuestions),
  entertainment: asPool(entertainmentQuestions),
  history: asPool(historyQuestions),
  arts: asPool(artsQuestions),
  science: asPool(scienceQuestions),
  sport: asPool(sportQuestions),
};

export const ALL_QUESTIONS: TriviaQuestion[] = WEDGE_IDS.flatMap(id => WEDGE_POOLS[id]);

/** Per-wedge counts — the setup screen uses these to warn about thin wedges. */
export const QUESTION_COUNTS: Record<WedgeId, number> = WEDGE_IDS.reduce(
  (acc, id) => { acc[id] = WEDGE_POOLS[id].length; return acc; },
  {} as Record<WedgeId, number>,
);

/** The thinnest enabled wedge — a game can't run longer than this allows. */
export function smallestPoolSize(wedges: WedgeId[]): number {
  if (wedges.length === 0) return 0;
  return Math.min(...wedges.map(w => QUESTION_COUNTS[w]));
}

// ─────────────────────────────────────────────
// SELECTION
// ─────────────────────────────────────────────

// Re-exported for callers that already import from this module. The
// implementation lives in utils/random so there is a single RNG entry point.
export { shuffle };

/**
 * Questions for a wedge, optionally narrowed by difficulty.
 * Falls back to the unfiltered wedge rather than returning nothing — a thin
 * wedge plus a narrow difficulty filter must never strand the game.
 */
export function getWedgePool(
  wedge: WedgeId,
  difficulties?: Array<1 | 2 | 3>,
): TriviaQuestion[] {
  const pool = WEDGE_POOLS[wedge] ?? [];
  if (!difficulties || difficulties.length === 0) return pool;
  const filtered = pool.filter(q => difficulties.includes(q.difficulty));
  return filtered.length > 0 ? filtered : pool;
}

/**
 * The on-screen answer order.
 *
 * `boolean` questions always render True then False — randomising a two-option
 * question just makes players re-read it for no gain. `multiple` questions get
 * a genuine shuffle so the answer isn't always in the same slot.
 */
export function buildOptions(question: TriviaQuestion): string[] {
  if (question.type === 'boolean') return ['True', 'False'];
  return shuffle([question.answer, ...question.distractors]);
}

export function isCorrect(question: TriviaQuestion, chosen: string): boolean {
  return chosen.trim().toLowerCase() === question.answer.trim().toLowerCase();
}

/**
 * Passed to the engine's resolve() when the answer timer expires.
 *
 * Lives here rather than in useTriviaEngine so grading stays entirely within
 * the React-free data layer — which is what lets tools/trivia-smoke.ts assert
 * it can never collide with a real answer.
 */
export const TIMEOUT_SENTINEL = '\u0000__timeout__';

// ─────────────────────────────────────────────
// PENALTIES
// ─────────────────────────────────────────────

/** Harder question missed → bigger drink. Mirrors Challenge intensity. */
const DIFFICULTY_PENALTY: Record<1 | 2 | 3, keyof typeof PENALTY> = {
  1: 'sip',
  2: 'small',
  3: 'medium',
};

/** Sips the answerer drinks for getting it wrong (or timing out). */
export function wrongAnswerSips(
  difficulty: 1 | 2 | 3,
  ctx: PenaltyContext = {},
): number {
  return getPenalty(DIFFICULTY_PENALTY[difficulty], ctx);
}

/** Sips the answerer gives out for winning a wedge. */
export function wedgeRewardSips(ctx: PenaltyContext = {}): number {
  return getPenalty('medium', ctx);
}

/** Cost of a failed steal — deliberately cheaper than a wrong answer. */
export function failedStealSips(ctx: PenaltyContext = {}): number {
  return getPenalty('small', ctx);
}

/** Bonus given out per correct answer once a player is on a hot streak. */
export function streakRewardSips(ctx: PenaltyContext = {}): number {
  return getPenalty('sip', ctx);
}

/** Correct answers in a row before the streak bonus kicks in. */
export const STREAK_THRESHOLD = 3;

export { formatPenalty as formatSips };
